"""add ocultar column to the model pedido

Revision ID: 06b27f92c5a4
Revises: add_min_selecoes_grupo
Create Date: 2026-04-23 21:28:39.518908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b27f92c5a4'
down_revision: Union[str, Sequence[str], None] = 'add_min_selecoes_grupo'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('oculto', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_pedido_oculto'), 'pedido', ['oculto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_oculto'), table_name='pedido')
    op.drop_column('pedido', 'oculto')
    op.create_table('parametros',
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auto_atendimento', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('delivery', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], name=op.f('parametros_estabelecimento_id_fkey')),
    sa.PrimaryKeyConstraint('estabelecimento_id', name=op.f('parametros_pkey'))
    )
    op.create_index(op.f('ix_parametros_estabelecimento_id'), 'parametros', ['estabelecimento_id'], unique=False)
    # ### end Alembic commands ###
