"""add nome to mesa

Revision ID: 098bb0b53b75
Revises: a54580fdb9dd
Create Date: 2026-04-20 10:31:21.098606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "098bb0b53b75"
down_revision: Union[str, Sequence[str], None] = "a54580fdb9dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("mesa", sa.Column("nome", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mesa", "nome")
    # ### end Alembic commands ###
