"""initial migration

Revision ID: 75d96829e15d
Revises:
Create Date: 2026-04-19 16:48:58.172499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "75d96829e15d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_filaimpressao_estabelecimento_id"), table_name="filaimpressao"
    )
    op.drop_index(op.f("ix_filaimpressao_pedido_id"), table_name="filaimpressao")
    op.drop_table("filaimpressao")
    op.drop_index(op.f("ix_reimpressao_estabelecimento_id"), table_name="reimpressao")
    op.drop_index(op.f("ix_reimpressao_pedido_id"), table_name="reimpressao")
    op.drop_table("reimpressao")
    op.create_index(
        op.f("ix_categoria_produto_produzido_por"),
        "categoria_produto",
        ["produzido_por"],
        unique=False,
    )
    op.create_foreign_key(
        None, "categoria_produto", "usuario", ["produzido_por"], ["id"]
    )
    op.alter_column(
        "pedido",
        "impresso",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_index(op.f("ix_pedido_impresso"), "pedido", ["impresso"], unique=False)
    op.create_index(
        op.f("ix_produto_produzido_por"), "produto", ["produzido_por"], unique=False
    )
    op.create_foreign_key(None, "produto", "usuario", ["produzido_por"], ["id"])
    op.add_column("usuario", sa.Column("master", sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE usuario SET master = false WHERE master IS NULL"))
    op.alter_column("usuario", "master", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuario", "master")
    op.drop_constraint(None, "produto", type_="foreignkey")
    op.drop_index(op.f("ix_produto_produzido_por"), table_name="produto")
    op.drop_index(op.f("ix_pedido_impresso"), table_name="pedido")
    op.alter_column(
        "pedido",
        "impresso",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_constraint(None, "categoria_produto", type_="foreignkey")
    op.drop_index(
        op.f("ix_categoria_produto_produzido_por"), table_name="categoria_produto"
    )
    op.create_table(
        "reimpressao",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("pedido_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "estabelecimento_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("impresso", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "criado_em", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reimpressao_pkey")),
    )
    op.create_index(
        op.f("ix_reimpressao_pedido_id"), "reimpressao", ["pedido_id"], unique=False
    )
    op.create_index(
        op.f("ix_reimpressao_estabelecimento_id"),
        "reimpressao",
        ["estabelecimento_id"],
        unique=False,
    )
    op.create_table(
        "filaimpressao",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("pedido_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "estabelecimento_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("impresso", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "criado_em", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("filaimpressao_pkey")),
    )
    op.create_index(
        op.f("ix_filaimpressao_pedido_id"), "filaimpressao", ["pedido_id"], unique=False
    )
    op.create_index(
        op.f("ix_filaimpressao_estabelecimento_id"),
        "filaimpressao",
        ["estabelecimento_id"],
        unique=False,
    )
    # ### end Alembic commands ###
