"""add imprime column to categoria produto model

Revision ID: 9162a9a0283a
Revises: c50bbc483fae
Create Date: 2026-04-24 11:07:11.608218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9162a9a0283a'
down_revision: Union[str, Sequence[str], None] = 'c50bbc483fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoria_produto', sa.Column('imprime', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categoria_produto', 'imprime')
    # ### end Alembic commands ###
