"""add master column

Revision ID: a54580fdb9dd
Revises: d626802dffa8
Create Date: 2026-04-19 17:59:45.180875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a54580fdb9dd"
down_revision: Union[str, Sequence[str], None] = "d626802dffa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usuario", sa.Column("master", sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE usuario SET master = false WHERE master IS NULL"))
    op.alter_column("usuario", "master", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuario", "master")
    # ### end Alembic commands ###
