"""add imprime column to produto model

Revision ID: c50bbc483fae
Revises: 06b27f92c5a4
Create Date: 2026-04-24 10:05:23.333827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50bbc483fae'
down_revision: Union[str, Sequence[str], None] = '06b27f92c5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('imprime', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'imprime')
    op.create_table('parametros',
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auto_atendimento', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('delivery', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], name=op.f('parametros_estabelecimento_id_fkey')),
    sa.PrimaryKeyConstraint('estabelecimento_id', name=op.f('parametros_pkey'))
    )
    op.create_index(op.f('ix_parametros_estabelecimento_id'), 'parametros', ['estabelecimento_id'], unique=False)
    # ### end Alembic commands ###
