# Use this file to define your development services and configurations.

services:

  postgres:
    image: postgres:16
    container_name: your-container-name
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - your_postgres_data:/var/lib/postgresql/data

volumes:
  your_postgres_data: